#!/usr/bin/env python3
"""
scripts/deploy.py
==================
Programmatic deployment helper for GenLayer Bradbury testnet.
Uses the genlayer-sdk Python client to deploy both contracts
and outputs their addresses for frontend configuration.

Usage:
    export PRIVATE_KEY=0x...
    python scripts/deploy.py --network bradbury

    # Or local node:
    python scripts/deploy.py --network local
"""

import os
import sys
import argparse
import json
import time

RESET = "\033[0m"
GREEN = "\033[92m"
CYAN  = "\033[96m"
YELLOW= "\033[93m"
RED   = "\033[91m"
BOLD  = "\033[1m"
DIM   = "\033[2m"

NETWORKS = {
    "bradbury": {
        "rpc":      "https://bradbury.genlayer.com",
        "chain_id": 42069,
        "explorer": "https://explorer.genlayer.com",
    },
    "local": {
        "rpc":      "http://localhost:4000",
        "chain_id": 1337,
        "explorer": None,
    },
}

CONTRACT_FILES = {
    "FactOracle":      "contracts/fact_oracle.py",
    "PredictionMarket": "contracts/prediction_market.py",
}


def print_banner():
    print(f"""
{BOLD}{CYAN}
  ╔══════════════════════════════════════════════════╗
  ║   GenLayer FactOracle — Deployment Script        ║
  ╚══════════════════════════════════════════════════╝
{RESET}""")


def deploy_mock(network_cfg: dict, private_key: str) -> dict[str, str]:
    """
    Simulated deployment (no real node connection).
    Replace with real genlayer-sdk calls for live deployment.
    """
    import random

    print(f"\n  {YELLOW}[SIMULATION MODE]{RESET} No real node connected.\n")
    print(f"  Real deployment requires: pip install genlayer-sdk\n")

    addresses = {}
    for name, filepath in CONTRACT_FILES.items():
        print(f"  Deploying {BOLD}{name}{RESET}...")
        time.sleep(0.8)

        # Generate deterministic mock address
        mock_addr = "0x" + "".join(random.choices("0123456789abcdef", k=40))
        mock_tx   = "0x" + "".join(random.choices("0123456789abcdef", k=64))

        print(f"    {GREEN}✓{RESET} Contract:    {mock_addr}")
        print(f"    {GREEN}✓{RESET} Transaction: {mock_tx[:20]}...")
        addresses[name] = mock_addr

    return addresses


def deploy_live(network_cfg: dict, private_key: str) -> dict[str, str]:
    """
    Live deployment using genlayer-sdk.
    Uncomment and install SDK to use.
    """
    try:
        from genlayer import Client  # type: ignore
    except ImportError:
        print(f"  {RED}genlayer-sdk not installed.{RESET}")
        print(f"  {DIM}pip install genlayer-sdk{RESET}")
        sys.exit(1)

    client = Client(rpc=network_cfg["rpc"])
    client.set_account(private_key)

    addresses = {}
    for name, filepath in CONTRACT_FILES.items():
        print(f"\n  Deploying {BOLD}{name}{RESET} from {filepath}...")

        with open(filepath) as f:
            source = f.read()

        tx_hash = client.deploy_contract(source=source)
        print(f"    Waiting for confirmation...")
        receipt  = client.wait_for_transaction(tx_hash)
        address  = receipt["contract_address"]

        print(f"    {GREEN}✓{RESET} Address:     {address}")
        print(f"    {GREEN}✓{RESET} Tx Hash:     {tx_hash[:20]}...")
        print(f"    {GREEN}✓{RESET} Block:       {receipt.get('block_number', 'N/A')}")

        if network_cfg["explorer"]:
            print(f"    {CYAN}→{RESET} Explorer: {network_cfg['explorer']}/tx/{tx_hash}")

        addresses[name] = address

    return addresses


def write_env_file(addresses: dict, network: str):
    """Write frontend .env.local with deployed addresses."""
    env_path = "frontend/.env.local"
    env_content = f"""# Auto-generated by scripts/deploy.py
# Network: {network}
# Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}

VITE_ORACLE_ADDRESS={addresses.get('FactOracle', '')}
VITE_MARKET_ADDRESS={addresses.get('PredictionMarket', '')}
VITE_RPC_URL={NETWORKS[network]['rpc']}
VITE_CHAIN_ID={NETWORKS[network]['chain_id']}
"""
    with open(env_path, "w") as f:
        f.write(env_content)

    print(f"\n  {GREEN}✓{RESET} Frontend config written to {env_path}")


def write_deployment_json(addresses: dict, network: str):
    """Save deployment addresses to JSON for reference."""
    data = {
        "network":    network,
        "timestamp":  time.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "contracts":  addresses,
        "rpc":        NETWORKS[network]["rpc"],
    }
    path = f"deployments/{network}.json"
    os.makedirs("deployments", exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)

    print(f"  {GREEN}✓{RESET} Deployment record saved to {path}")


def main():
    print_banner()

    parser = argparse.ArgumentParser(description="Deploy GenLayer FactOracle contracts")
    parser.add_argument("--network",  choices=["bradbury", "local"], default="local")
    parser.add_argument("--simulate", action="store_true", help="Simulate without real node")
    args = parser.parse_args()

    network_cfg = NETWORKS[args.network]
    private_key = os.environ.get("PRIVATE_KEY", "")

    print(f"  Network:  {BOLD}{args.network}{RESET}")
    print(f"  RPC:      {network_cfg['rpc']}")
    print(f"  Contracts: {', '.join(CONTRACT_FILES.keys())}")

    if not private_key and not args.simulate:
        print(f"\n  {YELLOW}⚠ PRIVATE_KEY not set. Running in simulation mode.{RESET}")
        print(f"  {DIM}Set it with: export PRIVATE_KEY=0x...{RESET}\n")
        args.simulate = True

    print(f"\n  {DIM}Starting deployment...{RESET}")

    if args.simulate or args.network == "local":
        addresses = deploy_mock(network_cfg, private_key)
    else:
        addresses = deploy_live(network_cfg, private_key)

    # Post-deployment
    write_env_file(addresses, args.network)
    write_deployment_json(addresses, args.network)

    print(f"""
{GREEN}{'═' * 60}{RESET}
{BOLD}  Deployment Complete!{RESET}

  FactOracle:       {addresses.get('FactOracle', 'N/A')}
  PredictionMarket: {addresses.get('PredictionMarket', 'N/A')}

  Next steps:
    cd frontend && npm run dev    # Start UI
    python cli/demo.py --network {args.network}   # CLI test
{GREEN}{'═' * 60}{RESET}
""")


if __name__ == "__main__":
    main()
